### ISSUE TITLE
Error running under macOS 

### ISSUE THREAD

**Issue by howdymatt** [drifting-in-space/botsh#1]
see the following when running a command on macOS:

```
 [info     ] Connecting to Docker...
 [error    ] Permission error connecting to Docker. Is Docker running? You may need to follow these instructions: https://docs.docker.com/engine/install/linux-postinstall/.
```

Instructions on the link provided are not relevant on macOS and the equivalent instructions do not work. I am able to pul land run other docker images on the CLI from the same user.

ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a

Docker for Mac: 4.19.0 (106363)

**Comment by paulgb** [comment]
Thanks for reporting. Unfortunately botsh swallowed all information from the exception that could have helped me troubleshoot this. I've pushed a new version (0.1.7) which will log the exception, which should be helpful here. I also suppress the linux instructions on non-linux systems.

I can't think of what might be causing the issue since I use botsh with Docker for Mac (4.18.0 in my case) as well, but if you can run the updated version to get an exception I'd be glad to have a look.

**Comment by paulgb** [comment]
Closing for now but feel free to resurrect if you run into it again.
